export default {
  formTitle: "My Form",
  nameFieldLabel: "Full Name",
  nameFieldPlaceholder: "Enter your Full Name",
  emailFieldLabel: "Email Id",
  emailFieldPlaceholder: "Enter your Email id",
  mobileNoFieldLabel: "Mobile Number",
  mobileNoFieldPlaceholder: "Enter your Mobile Number",
  passFieldLabel: "Password",
  passFieldPlaceholder: "Enter your Password",
  submitButtonLabel: "Submit",
  passwordRequired: "Password is required",
  emailRequired: "Email is required",
  nameRequired: "Name is required",
  phoneNorequired: "Mobile No. is required",
  invalidEmail: "Invalid Email",
  invalidMobileNo: "Invalid Mobile No",
  invalidPass: "Invalid Password",
};
